// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 
`include "p2p_250mhz_regslice_both.sv"

(* CORE_GENERATION_INFO="p2p_250mhz_p2p_250mhz,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu5p-flva2104-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.430200,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=118,HLS_SYN_LUT=321,HLS_VERSION=2023_2}" *)

module p2p_250mhz (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_qdma_h2c_TDATA,
        s_axis_qdma_h2c_TVALID,
        s_axis_qdma_h2c_TREADY,
        s_axis_qdma_h2c_TKEEP,
        s_axis_qdma_h2c_TUSER,
        s_axis_qdma_h2c_TLAST,
        s_axis_qdma_h2c_TID,
        s_axis_qdma_h2c_TDEST,
        m_axis_qdma_c2h_TDATA,
        m_axis_qdma_c2h_TVALID,
        m_axis_qdma_c2h_TREADY,
        m_axis_qdma_c2h_TKEEP,
        m_axis_qdma_c2h_TUSER,
        m_axis_qdma_c2h_TLAST,
        m_axis_qdma_c2h_TID,
        m_axis_qdma_c2h_TDEST,
        m_axis_adap_tx_250mhz_TDATA,
        m_axis_adap_tx_250mhz_TVALID,
        m_axis_adap_tx_250mhz_TREADY,
        m_axis_adap_tx_250mhz_TKEEP,
        m_axis_adap_tx_250mhz_TUSER,
        m_axis_adap_tx_250mhz_TLAST,
        m_axis_adap_tx_250mhz_TID,
        m_axis_adap_tx_250mhz_TDEST,
        s_axis_adap_rx_250mhz_TDATA,
        s_axis_adap_rx_250mhz_TVALID,
        s_axis_adap_rx_250mhz_TREADY,
        s_axis_adap_rx_250mhz_TKEEP,
        s_axis_adap_rx_250mhz_TUSER,
        s_axis_adap_rx_250mhz_TLAST,
        s_axis_adap_rx_250mhz_TID,
        s_axis_adap_rx_250mhz_TDEST
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [511:0] s_axis_qdma_h2c_TDATA;
input   s_axis_qdma_h2c_TVALID;
output   s_axis_qdma_h2c_TREADY;
input  [63:0] s_axis_qdma_h2c_TKEEP;
input  [15:0] s_axis_qdma_h2c_TUSER;
input  [0:0] s_axis_qdma_h2c_TLAST;
input  [15:0] s_axis_qdma_h2c_TID;
input  [15:0] s_axis_qdma_h2c_TDEST;
output  [511:0] m_axis_qdma_c2h_TDATA;
output   m_axis_qdma_c2h_TVALID;
input   m_axis_qdma_c2h_TREADY;
output  [63:0] m_axis_qdma_c2h_TKEEP;
output  [15:0] m_axis_qdma_c2h_TUSER;
output  [0:0] m_axis_qdma_c2h_TLAST;
output  [15:0] m_axis_qdma_c2h_TID;
output  [15:0] m_axis_qdma_c2h_TDEST;
output  [511:0] m_axis_adap_tx_250mhz_TDATA;
output   m_axis_adap_tx_250mhz_TVALID;
input   m_axis_adap_tx_250mhz_TREADY;
output  [63:0] m_axis_adap_tx_250mhz_TKEEP;
output  [15:0] m_axis_adap_tx_250mhz_TUSER;
output  [0:0] m_axis_adap_tx_250mhz_TLAST;
output  [15:0] m_axis_adap_tx_250mhz_TID;
output  [15:0] m_axis_adap_tx_250mhz_TDEST;
input  [511:0] s_axis_adap_rx_250mhz_TDATA;
input   s_axis_adap_rx_250mhz_TVALID;
output   s_axis_adap_rx_250mhz_TREADY;
input  [63:0] s_axis_adap_rx_250mhz_TKEEP;
input  [15:0] s_axis_adap_rx_250mhz_TUSER;
input  [0:0] s_axis_adap_rx_250mhz_TLAST;
input  [15:0] s_axis_adap_rx_250mhz_TID;
input  [15:0] s_axis_adap_rx_250mhz_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] in_i;
reg   [47:0] in_mac_addr_dst;
reg   [31:0] out_i;
reg    s_axis_qdma_h2c_TDATA_blk_n;
wire   [0:0] tmp_nbreadreq_fu_94_p8;
reg    m_axis_qdma_c2h_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_2_nbreadreq_fu_150_p8;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_2_reg_381;
reg    m_axis_adap_tx_250mhz_TDATA_blk_n;
wire   [0:0] icmp_ln53_fu_280_p2;
reg   [0:0] tmp_reg_340;
reg   [0:0] icmp_ln53_reg_377;
reg    s_axis_adap_rx_250mhz_TDATA_blk_n;
wire   [31:0] select_ln46_fu_262_p3;
reg    ap_predicate_op58_write_state1;
reg    ap_block_state1;
reg    ap_block_state1_io;
wire   [47:0] trunc_ln36_fu_246_p1;
wire   [0:0] icmp_ln34_fu_240_p2;
reg   [47:0] ap_sig_allocacmp_in_mac_addr_dst_load;
wire   [31:0] select_ln63_fu_326_p3;
reg    ap_predicate_op59_write_state2;
reg    ap_block_state2;
reg    ap_block_state2_io;
wire   [31:0] add_ln49_fu_256_p2;
wire   [31:0] add_ln75_fu_320_p2;
wire    regslice_both_m_axis_qdma_c2h_V_data_V_U_apdone_blk;
wire    regslice_both_m_axis_adap_tx_250mhz_V_data_V_U_apdone_blk;
reg    ap_block_state3;
reg    ap_block_state3_io;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    regslice_both_s_axis_qdma_h2c_V_data_V_U_apdone_blk;
wire   [511:0] s_axis_qdma_h2c_TDATA_int_regslice;
wire    s_axis_qdma_h2c_TVALID_int_regslice;
reg    s_axis_qdma_h2c_TREADY_int_regslice;
wire    regslice_both_s_axis_qdma_h2c_V_data_V_U_ack_in;
wire    regslice_both_s_axis_qdma_h2c_V_keep_V_U_apdone_blk;
wire   [63:0] s_axis_qdma_h2c_TKEEP_int_regslice;
wire    regslice_both_s_axis_qdma_h2c_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_qdma_h2c_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_qdma_h2c_V_user_V_U_apdone_blk;
wire   [15:0] s_axis_qdma_h2c_TUSER_int_regslice;
wire    regslice_both_s_axis_qdma_h2c_V_user_V_U_vld_out;
wire    regslice_both_s_axis_qdma_h2c_V_user_V_U_ack_in;
wire    regslice_both_s_axis_qdma_h2c_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_qdma_h2c_TLAST_int_regslice;
wire    regslice_both_s_axis_qdma_h2c_V_last_V_U_vld_out;
wire    regslice_both_s_axis_qdma_h2c_V_last_V_U_ack_in;
wire    regslice_both_s_axis_qdma_h2c_V_id_V_U_apdone_blk;
wire   [15:0] s_axis_qdma_h2c_TID_int_regslice;
wire    regslice_both_s_axis_qdma_h2c_V_id_V_U_vld_out;
wire    regslice_both_s_axis_qdma_h2c_V_id_V_U_ack_in;
wire    regslice_both_s_axis_qdma_h2c_V_dest_V_U_apdone_blk;
wire   [15:0] s_axis_qdma_h2c_TDEST_int_regslice;
wire    regslice_both_s_axis_qdma_h2c_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_qdma_h2c_V_dest_V_U_ack_in;
reg    m_axis_qdma_c2h_TVALID_int_regslice;
wire    m_axis_qdma_c2h_TREADY_int_regslice;
wire    regslice_both_m_axis_qdma_c2h_V_data_V_U_vld_out;
wire    regslice_both_m_axis_qdma_c2h_V_keep_V_U_apdone_blk;
wire    regslice_both_m_axis_qdma_c2h_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_qdma_c2h_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_qdma_c2h_V_user_V_U_apdone_blk;
wire    regslice_both_m_axis_qdma_c2h_V_user_V_U_ack_in_dummy;
wire    regslice_both_m_axis_qdma_c2h_V_user_V_U_vld_out;
wire    regslice_both_m_axis_qdma_c2h_V_last_V_U_apdone_blk;
wire    regslice_both_m_axis_qdma_c2h_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_qdma_c2h_V_last_V_U_vld_out;
wire    regslice_both_m_axis_qdma_c2h_V_id_V_U_apdone_blk;
wire    regslice_both_m_axis_qdma_c2h_V_id_V_U_ack_in_dummy;
wire    regslice_both_m_axis_qdma_c2h_V_id_V_U_vld_out;
wire    regslice_both_m_axis_qdma_c2h_V_dest_V_U_apdone_blk;
wire    regslice_both_m_axis_qdma_c2h_V_dest_V_U_ack_in_dummy;
wire    regslice_both_m_axis_qdma_c2h_V_dest_V_U_vld_out;
reg    m_axis_adap_tx_250mhz_TVALID_int_regslice;
wire    m_axis_adap_tx_250mhz_TREADY_int_regslice;
wire    regslice_both_m_axis_adap_tx_250mhz_V_data_V_U_vld_out;
wire    regslice_both_m_axis_adap_tx_250mhz_V_keep_V_U_apdone_blk;
wire    regslice_both_m_axis_adap_tx_250mhz_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_adap_tx_250mhz_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_adap_tx_250mhz_V_user_V_U_apdone_blk;
wire    regslice_both_m_axis_adap_tx_250mhz_V_user_V_U_ack_in_dummy;
wire    regslice_both_m_axis_adap_tx_250mhz_V_user_V_U_vld_out;
wire    regslice_both_m_axis_adap_tx_250mhz_V_last_V_U_apdone_blk;
wire    regslice_both_m_axis_adap_tx_250mhz_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_adap_tx_250mhz_V_last_V_U_vld_out;
wire    regslice_both_m_axis_adap_tx_250mhz_V_id_V_U_apdone_blk;
wire    regslice_both_m_axis_adap_tx_250mhz_V_id_V_U_ack_in_dummy;
wire    regslice_both_m_axis_adap_tx_250mhz_V_id_V_U_vld_out;
wire    regslice_both_m_axis_adap_tx_250mhz_V_dest_V_U_apdone_blk;
wire    regslice_both_m_axis_adap_tx_250mhz_V_dest_V_U_ack_in_dummy;
wire    regslice_both_m_axis_adap_tx_250mhz_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_adap_rx_250mhz_V_data_V_U_apdone_blk;
wire   [511:0] s_axis_adap_rx_250mhz_TDATA_int_regslice;
wire    s_axis_adap_rx_250mhz_TVALID_int_regslice;
reg    s_axis_adap_rx_250mhz_TREADY_int_regslice;
wire    regslice_both_s_axis_adap_rx_250mhz_V_data_V_U_ack_in;
wire    regslice_both_s_axis_adap_rx_250mhz_V_keep_V_U_apdone_blk;
wire   [63:0] s_axis_adap_rx_250mhz_TKEEP_int_regslice;
wire    regslice_both_s_axis_adap_rx_250mhz_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_adap_rx_250mhz_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_adap_rx_250mhz_V_user_V_U_apdone_blk;
wire   [15:0] s_axis_adap_rx_250mhz_TUSER_int_regslice;
wire    regslice_both_s_axis_adap_rx_250mhz_V_user_V_U_vld_out;
wire    regslice_both_s_axis_adap_rx_250mhz_V_user_V_U_ack_in;
wire    regslice_both_s_axis_adap_rx_250mhz_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_adap_rx_250mhz_TLAST_int_regslice;
wire    regslice_both_s_axis_adap_rx_250mhz_V_last_V_U_vld_out;
wire    regslice_both_s_axis_adap_rx_250mhz_V_last_V_U_ack_in;
wire    regslice_both_s_axis_adap_rx_250mhz_V_id_V_U_apdone_blk;
wire   [15:0] s_axis_adap_rx_250mhz_TID_int_regslice;
wire    regslice_both_s_axis_adap_rx_250mhz_V_id_V_U_vld_out;
wire    regslice_both_s_axis_adap_rx_250mhz_V_id_V_U_ack_in;
wire    regslice_both_s_axis_adap_rx_250mhz_V_dest_V_U_apdone_blk;
wire   [15:0] s_axis_adap_rx_250mhz_TDEST_int_regslice;
wire    regslice_both_s_axis_adap_rx_250mhz_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_adap_rx_250mhz_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 in_i = 32'd0;
#0 in_mac_addr_dst = 48'd0;
#0 out_i = 32'd0;
end

p2p_250mhz_regslice_both #(
    .DataWidth( 512 ))
regslice_both_s_axis_qdma_h2c_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TDATA),
    .vld_in(s_axis_qdma_h2c_TVALID),
    .ack_in(regslice_both_s_axis_qdma_h2c_V_data_V_U_ack_in),
    .data_out(s_axis_qdma_h2c_TDATA_int_regslice),
    .vld_out(s_axis_qdma_h2c_TVALID_int_regslice),
    .ack_out(s_axis_qdma_h2c_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_qdma_h2c_V_data_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 64 ))
regslice_both_s_axis_qdma_h2c_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TKEEP),
    .vld_in(s_axis_qdma_h2c_TVALID),
    .ack_in(regslice_both_s_axis_qdma_h2c_V_keep_V_U_ack_in),
    .data_out(s_axis_qdma_h2c_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_qdma_h2c_V_keep_V_U_vld_out),
    .ack_out(s_axis_qdma_h2c_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_qdma_h2c_V_keep_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_s_axis_qdma_h2c_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TUSER),
    .vld_in(s_axis_qdma_h2c_TVALID),
    .ack_in(regslice_both_s_axis_qdma_h2c_V_user_V_U_ack_in),
    .data_out(s_axis_qdma_h2c_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_qdma_h2c_V_user_V_U_vld_out),
    .ack_out(s_axis_qdma_h2c_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_qdma_h2c_V_user_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_qdma_h2c_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TLAST),
    .vld_in(s_axis_qdma_h2c_TVALID),
    .ack_in(regslice_both_s_axis_qdma_h2c_V_last_V_U_ack_in),
    .data_out(s_axis_qdma_h2c_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_qdma_h2c_V_last_V_U_vld_out),
    .ack_out(s_axis_qdma_h2c_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_qdma_h2c_V_last_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_s_axis_qdma_h2c_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TID),
    .vld_in(s_axis_qdma_h2c_TVALID),
    .ack_in(regslice_both_s_axis_qdma_h2c_V_id_V_U_ack_in),
    .data_out(s_axis_qdma_h2c_TID_int_regslice),
    .vld_out(regslice_both_s_axis_qdma_h2c_V_id_V_U_vld_out),
    .ack_out(s_axis_qdma_h2c_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_qdma_h2c_V_id_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_s_axis_qdma_h2c_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TDEST),
    .vld_in(s_axis_qdma_h2c_TVALID),
    .ack_in(regslice_both_s_axis_qdma_h2c_V_dest_V_U_ack_in),
    .data_out(s_axis_qdma_h2c_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_qdma_h2c_V_dest_V_U_vld_out),
    .ack_out(s_axis_qdma_h2c_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_qdma_h2c_V_dest_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 512 ))
regslice_both_m_axis_qdma_c2h_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TDATA_int_regslice),
    .vld_in(m_axis_qdma_c2h_TVALID_int_regslice),
    .ack_in(m_axis_qdma_c2h_TREADY_int_regslice),
    .data_out(m_axis_qdma_c2h_TDATA),
    .vld_out(regslice_both_m_axis_qdma_c2h_V_data_V_U_vld_out),
    .ack_out(m_axis_qdma_c2h_TREADY),
    .apdone_blk(regslice_both_m_axis_qdma_c2h_V_data_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 64 ))
regslice_both_m_axis_qdma_c2h_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TKEEP_int_regslice),
    .vld_in(m_axis_qdma_c2h_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_qdma_c2h_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_qdma_c2h_TKEEP),
    .vld_out(regslice_both_m_axis_qdma_c2h_V_keep_V_U_vld_out),
    .ack_out(m_axis_qdma_c2h_TREADY),
    .apdone_blk(regslice_both_m_axis_qdma_c2h_V_keep_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_m_axis_qdma_c2h_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TUSER_int_regslice),
    .vld_in(m_axis_qdma_c2h_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_qdma_c2h_V_user_V_U_ack_in_dummy),
    .data_out(m_axis_qdma_c2h_TUSER),
    .vld_out(regslice_both_m_axis_qdma_c2h_V_user_V_U_vld_out),
    .ack_out(m_axis_qdma_c2h_TREADY),
    .apdone_blk(regslice_both_m_axis_qdma_c2h_V_user_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_qdma_c2h_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TLAST_int_regslice),
    .vld_in(m_axis_qdma_c2h_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_qdma_c2h_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_qdma_c2h_TLAST),
    .vld_out(regslice_both_m_axis_qdma_c2h_V_last_V_U_vld_out),
    .ack_out(m_axis_qdma_c2h_TREADY),
    .apdone_blk(regslice_both_m_axis_qdma_c2h_V_last_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_m_axis_qdma_c2h_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TID_int_regslice),
    .vld_in(m_axis_qdma_c2h_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_qdma_c2h_V_id_V_U_ack_in_dummy),
    .data_out(m_axis_qdma_c2h_TID),
    .vld_out(regslice_both_m_axis_qdma_c2h_V_id_V_U_vld_out),
    .ack_out(m_axis_qdma_c2h_TREADY),
    .apdone_blk(regslice_both_m_axis_qdma_c2h_V_id_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_m_axis_qdma_c2h_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TDEST_int_regslice),
    .vld_in(m_axis_qdma_c2h_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_qdma_c2h_V_dest_V_U_ack_in_dummy),
    .data_out(m_axis_qdma_c2h_TDEST),
    .vld_out(regslice_both_m_axis_qdma_c2h_V_dest_V_U_vld_out),
    .ack_out(m_axis_qdma_c2h_TREADY),
    .apdone_blk(regslice_both_m_axis_qdma_c2h_V_dest_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 512 ))
regslice_both_m_axis_adap_tx_250mhz_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TDATA_int_regslice),
    .vld_in(m_axis_adap_tx_250mhz_TVALID_int_regslice),
    .ack_in(m_axis_adap_tx_250mhz_TREADY_int_regslice),
    .data_out(m_axis_adap_tx_250mhz_TDATA),
    .vld_out(regslice_both_m_axis_adap_tx_250mhz_V_data_V_U_vld_out),
    .ack_out(m_axis_adap_tx_250mhz_TREADY),
    .apdone_blk(regslice_both_m_axis_adap_tx_250mhz_V_data_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 64 ))
regslice_both_m_axis_adap_tx_250mhz_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TKEEP_int_regslice),
    .vld_in(m_axis_adap_tx_250mhz_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_adap_tx_250mhz_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_adap_tx_250mhz_TKEEP),
    .vld_out(regslice_both_m_axis_adap_tx_250mhz_V_keep_V_U_vld_out),
    .ack_out(m_axis_adap_tx_250mhz_TREADY),
    .apdone_blk(regslice_both_m_axis_adap_tx_250mhz_V_keep_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_m_axis_adap_tx_250mhz_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TUSER_int_regslice),
    .vld_in(m_axis_adap_tx_250mhz_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_adap_tx_250mhz_V_user_V_U_ack_in_dummy),
    .data_out(m_axis_adap_tx_250mhz_TUSER),
    .vld_out(regslice_both_m_axis_adap_tx_250mhz_V_user_V_U_vld_out),
    .ack_out(m_axis_adap_tx_250mhz_TREADY),
    .apdone_blk(regslice_both_m_axis_adap_tx_250mhz_V_user_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_adap_tx_250mhz_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TLAST_int_regslice),
    .vld_in(m_axis_adap_tx_250mhz_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_adap_tx_250mhz_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_adap_tx_250mhz_TLAST),
    .vld_out(regslice_both_m_axis_adap_tx_250mhz_V_last_V_U_vld_out),
    .ack_out(m_axis_adap_tx_250mhz_TREADY),
    .apdone_blk(regslice_both_m_axis_adap_tx_250mhz_V_last_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_m_axis_adap_tx_250mhz_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TID_int_regslice),
    .vld_in(m_axis_adap_tx_250mhz_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_adap_tx_250mhz_V_id_V_U_ack_in_dummy),
    .data_out(m_axis_adap_tx_250mhz_TID),
    .vld_out(regslice_both_m_axis_adap_tx_250mhz_V_id_V_U_vld_out),
    .ack_out(m_axis_adap_tx_250mhz_TREADY),
    .apdone_blk(regslice_both_m_axis_adap_tx_250mhz_V_id_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_m_axis_adap_tx_250mhz_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_qdma_h2c_TDEST_int_regslice),
    .vld_in(m_axis_adap_tx_250mhz_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_adap_tx_250mhz_V_dest_V_U_ack_in_dummy),
    .data_out(m_axis_adap_tx_250mhz_TDEST),
    .vld_out(regslice_both_m_axis_adap_tx_250mhz_V_dest_V_U_vld_out),
    .ack_out(m_axis_adap_tx_250mhz_TREADY),
    .apdone_blk(regslice_both_m_axis_adap_tx_250mhz_V_dest_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 512 ))
regslice_both_s_axis_adap_rx_250mhz_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TDATA),
    .vld_in(s_axis_adap_rx_250mhz_TVALID),
    .ack_in(regslice_both_s_axis_adap_rx_250mhz_V_data_V_U_ack_in),
    .data_out(s_axis_adap_rx_250mhz_TDATA_int_regslice),
    .vld_out(s_axis_adap_rx_250mhz_TVALID_int_regslice),
    .ack_out(s_axis_adap_rx_250mhz_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_adap_rx_250mhz_V_data_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 64 ))
regslice_both_s_axis_adap_rx_250mhz_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TKEEP),
    .vld_in(s_axis_adap_rx_250mhz_TVALID),
    .ack_in(regslice_both_s_axis_adap_rx_250mhz_V_keep_V_U_ack_in),
    .data_out(s_axis_adap_rx_250mhz_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_adap_rx_250mhz_V_keep_V_U_vld_out),
    .ack_out(s_axis_adap_rx_250mhz_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_adap_rx_250mhz_V_keep_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_s_axis_adap_rx_250mhz_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TUSER),
    .vld_in(s_axis_adap_rx_250mhz_TVALID),
    .ack_in(regslice_both_s_axis_adap_rx_250mhz_V_user_V_U_ack_in),
    .data_out(s_axis_adap_rx_250mhz_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_adap_rx_250mhz_V_user_V_U_vld_out),
    .ack_out(s_axis_adap_rx_250mhz_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_adap_rx_250mhz_V_user_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_adap_rx_250mhz_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TLAST),
    .vld_in(s_axis_adap_rx_250mhz_TVALID),
    .ack_in(regslice_both_s_axis_adap_rx_250mhz_V_last_V_U_ack_in),
    .data_out(s_axis_adap_rx_250mhz_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_adap_rx_250mhz_V_last_V_U_vld_out),
    .ack_out(s_axis_adap_rx_250mhz_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_adap_rx_250mhz_V_last_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_s_axis_adap_rx_250mhz_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TID),
    .vld_in(s_axis_adap_rx_250mhz_TVALID),
    .ack_in(regslice_both_s_axis_adap_rx_250mhz_V_id_V_U_ack_in),
    .data_out(s_axis_adap_rx_250mhz_TID_int_regslice),
    .vld_out(regslice_both_s_axis_adap_rx_250mhz_V_id_V_U_vld_out),
    .ack_out(s_axis_adap_rx_250mhz_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_adap_rx_250mhz_V_id_V_U_apdone_blk)
);

p2p_250mhz_regslice_both #(
    .DataWidth( 16 ))
regslice_both_s_axis_adap_rx_250mhz_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_adap_rx_250mhz_TDEST),
    .vld_in(s_axis_adap_rx_250mhz_TVALID),
    .ack_in(regslice_both_s_axis_adap_rx_250mhz_V_dest_V_U_ack_in),
    .data_out(s_axis_adap_rx_250mhz_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_adap_rx_250mhz_V_dest_V_U_vld_out),
    .ack_out(s_axis_adap_rx_250mhz_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_adap_rx_250mhz_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln53_reg_377 <= icmp_ln53_fu_280_p2;
        tmp_reg_340 <= tmp_nbreadreq_fu_94_p8;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (tmp_nbreadreq_fu_94_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        in_i <= select_ln46_fu_262_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (tmp_nbreadreq_fu_94_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln34_fu_240_p2 == 1'd1))) begin
        in_mac_addr_dst <= trunc_ln36_fu_246_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2)) & (tmp_2_nbreadreq_fu_150_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_i <= select_ln63_fu_326_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_2_reg_381 <= tmp_2_nbreadreq_fu_150_p8;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_94_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln34_fu_240_p2 == 1'd1))) begin
        ap_sig_allocacmp_in_mac_addr_dst_load = trunc_ln36_fu_246_p1;
    end else begin
        ap_sig_allocacmp_in_mac_addr_dst_load = in_mac_addr_dst;
    end
end

always @ (*) begin
    if ((((icmp_ln53_reg_377 == 1'd1) & (tmp_reg_340 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln53_fu_280_p2 == 1'd1) & (tmp_nbreadreq_fu_94_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        m_axis_adap_tx_250mhz_TDATA_blk_n = m_axis_adap_tx_250mhz_TREADY_int_regslice;
    end else begin
        m_axis_adap_tx_250mhz_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op58_write_state1 == 1'b1))) begin
        m_axis_adap_tx_250mhz_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_adap_tx_250mhz_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_381 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((tmp_2_nbreadreq_fu_150_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        m_axis_qdma_c2h_TDATA_blk_n = m_axis_qdma_c2h_TREADY_int_regslice;
    end else begin
        m_axis_qdma_c2h_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2)) & (tmp_2_nbreadreq_fu_150_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axis_qdma_c2h_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_qdma_c2h_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_nbreadreq_fu_150_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        s_axis_adap_rx_250mhz_TDATA_blk_n = s_axis_adap_rx_250mhz_TVALID_int_regslice;
    end else begin
        s_axis_adap_rx_250mhz_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2)) & (tmp_2_nbreadreq_fu_150_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        s_axis_adap_rx_250mhz_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_adap_rx_250mhz_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_94_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        s_axis_qdma_h2c_TDATA_blk_n = s_axis_qdma_h2c_TVALID_int_regslice;
    end else begin
        s_axis_qdma_h2c_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (tmp_nbreadreq_fu_94_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_qdma_h2c_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_qdma_h2c_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln49_fu_256_p2 = (in_i + 32'd1);

assign add_ln75_fu_320_p2 = (out_i + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | ((tmp_nbreadreq_fu_94_p8 == 1'd1) & (s_axis_qdma_h2c_TVALID_int_regslice == 1'b0)) | ((m_axis_adap_tx_250mhz_TREADY_int_regslice == 1'b0) & (ap_predicate_op58_write_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1_io = ((m_axis_adap_tx_250mhz_TREADY_int_regslice == 1'b0) & (ap_predicate_op58_write_state1 == 1'b1));
end

always @ (*) begin
    ap_block_state2 = (((tmp_2_nbreadreq_fu_150_p8 == 1'd1) & (s_axis_adap_rx_250mhz_TVALID_int_regslice == 1'b0)) | ((tmp_2_nbreadreq_fu_150_p8 == 1'd1) & (m_axis_qdma_c2h_TREADY_int_regslice == 1'b0)) | ((m_axis_adap_tx_250mhz_TREADY_int_regslice == 1'b0) & (ap_predicate_op59_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_io = (((tmp_2_nbreadreq_fu_150_p8 == 1'd1) & (m_axis_qdma_c2h_TREADY_int_regslice == 1'b0)) | ((m_axis_adap_tx_250mhz_TREADY_int_regslice == 1'b0) & (ap_predicate_op59_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3 = ((regslice_both_m_axis_adap_tx_250mhz_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_m_axis_qdma_c2h_V_data_V_U_apdone_blk == 1'b1) | ((tmp_2_reg_381 == 1'd1) & (m_axis_qdma_c2h_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state3_io = ((tmp_2_reg_381 == 1'd1) & (m_axis_qdma_c2h_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_predicate_op58_write_state1 = ((icmp_ln53_fu_280_p2 == 1'd1) & (tmp_nbreadreq_fu_94_p8 == 1'd1));
end

always @ (*) begin
    ap_predicate_op59_write_state2 = ((icmp_ln53_reg_377 == 1'd1) & (tmp_reg_340 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign icmp_ln34_fu_240_p2 = ((in_i == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_280_p2 = ((ap_sig_allocacmp_in_mac_addr_dst_load == 48'd170653684681074) ? 1'b1 : 1'b0);

assign m_axis_adap_tx_250mhz_TVALID = regslice_both_m_axis_adap_tx_250mhz_V_data_V_U_vld_out;

assign m_axis_qdma_c2h_TVALID = regslice_both_m_axis_qdma_c2h_V_data_V_U_vld_out;

assign s_axis_adap_rx_250mhz_TREADY = regslice_both_s_axis_adap_rx_250mhz_V_data_V_U_ack_in;

assign s_axis_qdma_h2c_TREADY = regslice_both_s_axis_qdma_h2c_V_data_V_U_ack_in;

assign select_ln46_fu_262_p3 = ((s_axis_qdma_h2c_TLAST_int_regslice[0:0] == 1'b1) ? 32'd0 : add_ln49_fu_256_p2);

assign select_ln63_fu_326_p3 = ((s_axis_adap_rx_250mhz_TLAST_int_regslice[0:0] == 1'b1) ? 32'd0 : add_ln75_fu_320_p2);

assign tmp_2_nbreadreq_fu_150_p8 = s_axis_adap_rx_250mhz_TVALID_int_regslice;

assign tmp_nbreadreq_fu_94_p8 = s_axis_qdma_h2c_TVALID_int_regslice;

assign trunc_ln36_fu_246_p1 = s_axis_qdma_h2c_TDATA_int_regslice[47:0];

endmodule //p2p_250mhz
